import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";

import Layout from "@/components/Layout";
import Login from "@/components/Layout/Login";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout({
  children,
}: {
  children: React.ReactNode;
  message: string;
}) {
  const token = cookies()?.get("user")?.value;
  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout>{children}</Layout>
        {/* {token ? <Layout>{children}</Layout> : <Login />} */}
      </body>
    </html>
  );
}
export default RootLayout;
