import type { Metadata } from "next";
import { Inter } from "next/font/google";

import UserAuth from "@/components/HOC/UserAuth";
import Layout from "@/components/Layout";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout({
  children,
}: {
  children: React.ReactNode;
  message: string;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
export default UserAuth(RootLayout);
